// Autogenerated by Thrift Compiler (0.9.3)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package bookservice

import (
	"bytes"
	"fmt"
	"git.apache.org/thrift.git/lib/go/thrift"
	"github.com/wangxingge/thrift_clientpool/examples/entity"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = bytes.Equal

var _ = entity.GoUnusedProtection__

type KeepAliveService interface {
	// Parameters:
	//  - ClientId
	DefaultKeepAlive(clientId string) (r bool, err error)
}

type KeepAliveServiceClient struct {
	Transport       thrift.TTransport
	ProtocolFactory thrift.TProtocolFactory
	InputProtocol   thrift.TProtocol
	OutputProtocol  thrift.TProtocol
	SeqId           int32
}

func NewKeepAliveServiceClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *KeepAliveServiceClient {
	return &KeepAliveServiceClient{Transport: t,
		ProtocolFactory: f,
		InputProtocol:   f.GetProtocol(t),
		OutputProtocol:  f.GetProtocol(t),
		SeqId:           0,
	}
}

func NewKeepAliveServiceClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *KeepAliveServiceClient {
	return &KeepAliveServiceClient{Transport: t,
		ProtocolFactory: nil,
		InputProtocol:   iprot,
		OutputProtocol:  oprot,
		SeqId:           0,
	}
}

// Parameters:
//  - ClientId
func (p *KeepAliveServiceClient) DefaultKeepAlive(clientId string) (r bool, err error) {
	if err = p.sendDefaultKeepAlive(clientId); err != nil {
		return
	}
	return p.recvDefaultKeepAlive()
}

func (p *KeepAliveServiceClient) sendDefaultKeepAlive(clientId string) (err error) {
	oprot := p.OutputProtocol
	if oprot == nil {
		oprot = p.ProtocolFactory.GetProtocol(p.Transport)
		p.OutputProtocol = oprot
	}
	p.SeqId++
	if err = oprot.WriteMessageBegin("DefaultKeepAlive", thrift.CALL, p.SeqId); err != nil {
		return
	}
	args := KeepAliveServiceDefaultKeepAliveArgs{
		ClientId: clientId,
	}
	if err = args.Write(oprot); err != nil {
		return
	}
	if err = oprot.WriteMessageEnd(); err != nil {
		return
	}
	return oprot.Flush()
}

func (p *KeepAliveServiceClient) recvDefaultKeepAlive() (value bool, err error) {
	iprot := p.InputProtocol
	if iprot == nil {
		iprot = p.ProtocolFactory.GetProtocol(p.Transport)
		p.InputProtocol = iprot
	}
	method, mTypeId, seqId, err := iprot.ReadMessageBegin()
	if err != nil {
		return
	}
	if method != "DefaultKeepAlive" {
		err = thrift.NewTApplicationException(thrift.WRONG_METHOD_NAME, "DefaultKeepAlive failed: wrong method name")
		return
	}
	if p.SeqId != seqId {
		err = thrift.NewTApplicationException(thrift.BAD_SEQUENCE_ID, "DefaultKeepAlive failed: out of sequence response")
		return
	}
	if mTypeId == thrift.EXCEPTION {
		error49 := thrift.NewTApplicationException(thrift.UNKNOWN_APPLICATION_EXCEPTION, "Unknown Exception")
		var error50 error
		error50, err = error49.Read(iprot)
		if err != nil {
			return
		}
		if err = iprot.ReadMessageEnd(); err != nil {
			return
		}
		err = error50
		return
	}
	if mTypeId != thrift.REPLY {
		err = thrift.NewTApplicationException(thrift.INVALID_MESSAGE_TYPE_EXCEPTION, "DefaultKeepAlive failed: invalid message type")
		return
	}
	result := KeepAliveServiceDefaultKeepAliveResult{}
	if err = result.Read(iprot); err != nil {
		return
	}
	if err = iprot.ReadMessageEnd(); err != nil {
		return
	}
	value = result.GetSuccess()
	return
}

type KeepAliveServiceProcessor struct {
	processorMap map[string]thrift.TProcessorFunction
	handler      KeepAliveService
}

func (p *KeepAliveServiceProcessor) AddToProcessorMap(key string, processor thrift.TProcessorFunction) {
	p.processorMap[key] = processor
}

func (p *KeepAliveServiceProcessor) GetProcessorFunction(key string) (processor thrift.TProcessorFunction, ok bool) {
	processor, ok = p.processorMap[key]
	return processor, ok
}

func (p *KeepAliveServiceProcessor) ProcessorMap() map[string]thrift.TProcessorFunction {
	return p.processorMap
}

func NewKeepAliveServiceProcessor(handler KeepAliveService) *KeepAliveServiceProcessor {

	self51 := &KeepAliveServiceProcessor{handler: handler, processorMap: make(map[string]thrift.TProcessorFunction)}
	self51.processorMap["DefaultKeepAlive"] = &keepAliveServiceProcessorDefaultKeepAlive{handler: handler}
	return self51
}

func (p *KeepAliveServiceProcessor) Process(iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	name, _, seqId, err := iprot.ReadMessageBegin()
	if err != nil {
		return false, err
	}
	if processor, ok := p.GetProcessorFunction(name); ok {
		return processor.Process(seqId, iprot, oprot)
	}
	iprot.Skip(thrift.STRUCT)
	iprot.ReadMessageEnd()
	x52 := thrift.NewTApplicationException(thrift.UNKNOWN_METHOD, "Unknown function "+name)
	oprot.WriteMessageBegin(name, thrift.EXCEPTION, seqId)
	x52.Write(oprot)
	oprot.WriteMessageEnd()
	oprot.Flush()
	return false, x52

}

type keepAliveServiceProcessorDefaultKeepAlive struct {
	handler KeepAliveService
}

func (p *keepAliveServiceProcessorDefaultKeepAlive) Process(seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	args := KeepAliveServiceDefaultKeepAliveArgs{}
	if err = args.Read(iprot); err != nil {
		iprot.ReadMessageEnd()
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err.Error())
		oprot.WriteMessageBegin("DefaultKeepAlive", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush()
		return false, err
	}

	iprot.ReadMessageEnd()
	result := KeepAliveServiceDefaultKeepAliveResult{}
	var retval bool
	var err2 error
	if retval, err2 = p.handler.DefaultKeepAlive(args.ClientId); err2 != nil {
		x := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing DefaultKeepAlive: "+err2.Error())
		oprot.WriteMessageBegin("DefaultKeepAlive", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush()
		return true, err2
	} else {
		result.Success = &retval
	}
	if err2 = oprot.WriteMessageBegin("DefaultKeepAlive", thrift.REPLY, seqId); err2 != nil {
		err = err2
	}
	if err2 = result.Write(oprot); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.WriteMessageEnd(); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.Flush(); err == nil && err2 != nil {
		err = err2
	}
	if err != nil {
		return
	}
	return true, err
}

// HELPER FUNCTIONS AND STRUCTURES

// Attributes:
//  - ClientId
type KeepAliveServiceDefaultKeepAliveArgs struct {
	ClientId string `thrift:"clientId,1" json:"clientId"`
}

func NewKeepAliveServiceDefaultKeepAliveArgs() *KeepAliveServiceDefaultKeepAliveArgs {
	return &KeepAliveServiceDefaultKeepAliveArgs{}
}

func (p *KeepAliveServiceDefaultKeepAliveArgs) GetClientId() string {
	return p.ClientId
}
func (p *KeepAliveServiceDefaultKeepAliveArgs) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.readField1(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *KeepAliveServiceDefaultKeepAliveArgs) readField1(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 1: ", err)
	} else {
		p.ClientId = v
	}
	return nil
}

func (p *KeepAliveServiceDefaultKeepAliveArgs) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("DefaultKeepAlive_args"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if err := p.writeField1(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *KeepAliveServiceDefaultKeepAliveArgs) writeField1(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("clientId", thrift.STRING, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:clientId: ", p), err)
	}
	if err := oprot.WriteString(string(p.ClientId)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.clientId (1) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:clientId: ", p), err)
	}
	return err
}

func (p *KeepAliveServiceDefaultKeepAliveArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KeepAliveServiceDefaultKeepAliveArgs(%+v)", *p)
}

// Attributes:
//  - Success
type KeepAliveServiceDefaultKeepAliveResult struct {
	Success *bool `thrift:"success,0" json:"success,omitempty"`
}

func NewKeepAliveServiceDefaultKeepAliveResult() *KeepAliveServiceDefaultKeepAliveResult {
	return &KeepAliveServiceDefaultKeepAliveResult{}
}

var KeepAliveServiceDefaultKeepAliveResult_Success_DEFAULT bool

func (p *KeepAliveServiceDefaultKeepAliveResult) GetSuccess() bool {
	if !p.IsSetSuccess() {
		return KeepAliveServiceDefaultKeepAliveResult_Success_DEFAULT
	}
	return *p.Success
}
func (p *KeepAliveServiceDefaultKeepAliveResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *KeepAliveServiceDefaultKeepAliveResult) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 0:
			if err := p.readField0(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *KeepAliveServiceDefaultKeepAliveResult) readField0(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadBool(); err != nil {
		return thrift.PrependError("error reading field 0: ", err)
	} else {
		p.Success = &v
	}
	return nil
}

func (p *KeepAliveServiceDefaultKeepAliveResult) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("DefaultKeepAlive_result"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if err := p.writeField0(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *KeepAliveServiceDefaultKeepAliveResult) writeField0(oprot thrift.TProtocol) (err error) {
	if p.IsSetSuccess() {
		if err := oprot.WriteFieldBegin("success", thrift.BOOL, 0); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 0:success: ", p), err)
		}
		if err := oprot.WriteBool(bool(*p.Success)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.success (0) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 0:success: ", p), err)
		}
	}
	return err
}

func (p *KeepAliveServiceDefaultKeepAliveResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KeepAliveServiceDefaultKeepAliveResult(%+v)", *p)
}
